### ISSUE TITLE
Konira is removing the current directory from the PYTHON path

### ISSUE THREAD

**Issue by igorgue** [alfredodeza/konira#12]
I tried to run the example here: http://konira.cafepais.com/docs/basic_structure.html

And it's unable to find the current directory modules. A look at sys.path shows that the first path isn't ''.

This is the output I get

```
(testingkonira)‹python-2.7.2› ~/code/testingkonira konira 
Errors:
-------
1 ==> ImportError: No module named foo
File: /Users/igor/code/testingkonira/case_foo.py:1:
No cases/specs collected.
```

A workaround this issue would be:

```
(testingkonira)‹python-2.7.2› ~/code/testingkonira PYTHONPATH=. konira    
the foo class
    It has a bar method that always returns true
All 1 spec passed in 0.127 secs.
```

**Comment by igorgue** [comment]
It also fixes this if you add `./` to your `.zshrc`:

```
export PYTHONPATH=./:"`brew --prefix python`/lib/python2.7/site-packages"
```

**Comment by alfredodeza** [comment]
That is a workaround but this _is_ a Konira issue. 

Thanks for reporting and it has been fixed with this commit: https://github.com/alfredodeza/konira/commit/2d72f7998a69b2a22d4f80b99e59330f64ee07c3

Could you please check out the HEAD of this repository and see if it works for you? Pending your response to close this ticket.

**Comment by igorgue** [comment]
It works, thanks for fixing it quickly.

**Comment by alfredodeza** [comment]
The new version with the bug fixes you reported has been pushed to PyPi: http://pypi.python.org/pypi/konira
