### ISSUE TITLE
Inherit from another TestCase

### ISSUE THREAD

**Issue by igorgue** [alfredodeza/konira#16]
How do you inherit from another test case? e.g.:

```
from flaskext.testing import TestCase
```

**Comment by alfredodeza** [comment]
Sorry Igorgue, I have not documented this because I wasn't sure what the best way to approach the problem was.

I just recently started adding tests for it so I could validate my intentions.

The way to inherit is pretty easy:

```
class Foo(object):

    def bar(self):
        return True


describe "working with inheritance", Foo:                                                                                                                                                             

    it "knows about parent methods":
        assert self.bar is True
```

So that gives you access to parent methods but I am thinking you want to subclass because you
need to get some re-usable code out of the way right? In that case you need to use Konira's private methods
that will get called when the DSL does its translation.

This is an example of that happening (not complete though, I promise some docs):

```
class Helpers(object):
    """ This class shows how Konira contructor helpers work                                                                                                                                           
    so that they are individually tested afterwards
    """

    def _before_all(self):
        """ before all """
        pass


    def _before_each(self):
        """ before each """
       pass


    def _after_each(self):
        """" after each """
        pass


    def _after_all(self):
        """" after all """
       pass
```

**Comment by igorgue** [comment]
Hi,

Thanks for the response. What I'd like to do is something like this:

http://packages.python.org/Flask-Testing/#writing-unit-tests

See the part that says:

```
response = self.client.get("/ajax/")
```

I want to use "client" from the base class.

Idea: I'd say if you document how to use Konira with the Django test client then you cover a good amount of people that might be searching for "Konira and Django".

**Comment by alfredodeza** [comment]
I thought my previous example showed a bit how you could achieve calling `self.client.get`.

If you have `TestCase` coming from Flask, you do inheritance like so:

```
describe "testing a view in Flask", TestCase:

    it "can resolve requesting ajax":
        response = self.client.get('/ajax/')
        assert response.status == 200
```

Also, I was not aware that people wanted to use Konira with Django. I've used Django before and found it to be a _pain_ to deal with tests. If you know how the Django test runner works and how to extend it I can provide any/all information to hook up Konira properly.

**Comment by igorgue** [comment]
I'd probably write the docs when I get it to work.

The Flask TestCase says you must define this:

```
def create_app(self):

    app = Flask(__name__)
    app.config['TESTING'] = True
    return app
```

I might be missing something but how do you do that on konira? would a it "create_app" do it?

**Comment by igorgue** [comment]
@alfredodeza yeah I got that, but looks like the test runner isn't working with flaskext.testing.TestCase.

**Comment by alfredodeza** [comment]
Ah ok, so you need to have that method, well it is just a matter of adding it to the parent class if you want that, otherwise you can just add the method inside the `describe` section.

You need to see `describe` as a Python class and `it` as a method :) Anything that a normal Python class would accept, would work inside a `describe`.

Does that make sense?

Also worth noting is that you could create your own TestCase that incorporates your Flask app:

```
class MyTestCase(Flask.TestCase):

    def create_app(self):
        ...
```

And then use it in Konira by inheriting from it:

```
describe "my flask application", MyTestCase:
    ...
```

**Comment by alfredodeza** [comment]
You know, it may be because Flask's TestCase depends on setUp being called ! Have you tried adding a `super` call in `before each`  that calls setup?

**Comment by igorgue** [comment]
No, I took a different approach, let me post the code here:

https://gist.github.com/6b044c5e64b03f8a6518

Is not longer using TestCase, but it's ok I'll try later, you you said makes total sense.
