### ISSUE TITLE
Tests are implicitly sorted

### ISSUE THREAD

**Issue by lweberk** [alfredodeza/konira#19]
Hi,

Tests get sorted by alphabet, instead of being run sequentially as they are defined.

You might argue about; why would you have sequential state in your tests...

Small example:

``` python
from myserializationlib import dump, load

describe "testing my serialization lib":
    before all:
        self.raw = "asd"
        self.serialized = None

    it "serliaziles correctly":
        self.serialized = dump(self.raw)
        assert self.serialized == b'617364'

    it "deserializes correctly":
        assert self.raw == load(self.serialized)
```

This results in "deserializes correctly" being called before "serializes correctly" ("D" before "S").

A workaroud would be to prefix a letter, but its beyond ugly. The tokenizer is sensitive to everything not pertaining to :alpha:, so numbers and any other chars are out of the question.

Am I missing something? Or should I look into a fix?

Sincerely,
~lweberk

**Comment by alfredodeza** [comment]
I know of this behavior, and it is what I was expecting as that is how `unittest` does it (for example).

Interesting enough, `py.test` does it differently, respecting the order tests are defined. The reason why this happens is because at collection time, `konira` loads the code from the path and looks into its modules by using the builtin `dir()`.

This builtin returns an alphabetized list of names from an object's attributes.

`konira

**Comment by alfredodeza** [comment]
I know of this behavior, and it is what I was expecting as that is how `unittest` does it (for example).

Interesting enough, `py.test` does it differently, respecting the order tests are defined. The reason why this happens is because at collection time, `konira` loads the code from the path and looks into its modules by using the builtin `dir()`.

This builtin returns an alphabetized list of names from an object's attributes.

`konira` wasn't built with extensibility in mind (at least, not for the test runner) so this will need to be made an option.

Maybe something in the DSL could explicitly set the arrangement of tests? I would prefer extending the DSL rather than touching the test runner.

Something like a class attribute where you can define an `order`:

```
describe "some test":

    order = my_ordering_function

...
```

This ordering function would be given the list of modules for the given class and it would return whatever it does with that list.

That would solve one part of the problem though, I am not entirely sure (right now) how to respect the current order of tests as they exist in the module (non-alphabetized).

**Comment by lweberk** [comment]
After having a lot of fun reading your code. Really interesting approach. I just went against the wall with what you where already saying; dir() just sorts, whether you like it or not, and I second your conclusion that AFAIK there is no way around it.

You where mentioning to extend the DSL by something to explicitly order the cases... It would both be not really elegant, nor very easy to use.
I guess the best way to tackle it is by supporting numbers and various chars in the definition name, thus making "1 - Test C", "2 - Test A" etc. or similar possible. Its a quite elegant way of optionally and explicitly voicing the wish for a certain order to be maintained at execution.
This wont be possible though with the use of the interpreters tokenizer frontend. Though a really interesting approach, it will always conflict with the native Python syntax (tokenizer does not expect anything else) so basically its an endless cheating around what the tokenizer could dislike or simply not expect.

This leads me to the question; would you consider taking in a reimplementation of the tokenizer frontend? Basically:
**[self built lexer]** --> **python tokenizer tokens** --> **.untokenize(tokens)** --> **python sources** --> **compile** --> **runner**

**Comment by alfredodeza** [comment]
I hope the _fun_ was really fun :)

I'm pretty sure there is a way around this, I discussed it briefly with the `py.test` team and it looks like something can be done here.

The process of getting to the point where Konira needs to go through the modules is past the tokenizer portion, not sure if you already know this and are suggesting otherwise. Do you believe that there is no way to inspect the modules without using `dir()` and getting an alphabetized sorting?

**Comment by lweberk** [comment]
Yepp, no sarcasm intended. It was my first time to see the use of tokenize in action :P. Made it really interesting. Code is also nice and easy to read.

To elaborate on what I was trying to put forth as a solution;
There are basically two places to solve the issue of getting implicit alphabetical sorting before execution:
1) Somehow work around the implicit sorting of dir() by figuring out how to replicate its behaviour but without its sorting side effect... difficult if not outright not feasible. This happens with the tokenstream already compiled and has nothing to do with the lexing of the original konira tests.
2) Modify the lexer to support :alphanum: and even some special chars like "-" for instance. This way you actually make use of the alphabetic sorting property of dir() by prefixing the test description string with a number or anything that would result in arbitrarily getting one test to be alphabetically in front of some other test that you want to be executed afterwards. Ex.:

``` python
    it "1 - serliaziles correctly":                     # Prefix "1" 
        self.serialized = dump(self.raw)
        assert self.serialized == b'617364'

    it "2 - deserializes correctly":                  # Prefix "2"
        assert self.raw == load(self.serialized)
```

This way it stays optional and contained within the current state of features. No extra stuff. Just more freedom of name definition.
Unfortunately this is not directly possible, since it is basically part of the interpreter. So it would be reasonable to build a own lexer that builds the python tokenlist from scratch and only uses the build in lexer to tokenize the actual method implementations.

A collateral projection would be the eventual opening of the future possibility to support any ASCII char in the name definitions (lexer limitation is out of the way). It would require a metadata lookup though, since you would still need valid method and class names for the python compiler to work, thus loosing anything but a supported subset of ASCII in the naming along the way. Nevertheless it opens many possibilities to shape test names in any way users like.
